version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: db_shop
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  my-db:
